config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'posts#index', as: 'home'

   get 'about' => 'pages#about'

  resources :posts do
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  

end

app/models/post.rb
class Post < ActiveRecord::Base
   has_many :comments, dependent: :destroy
   belongs_to :category
   validates_presence_of :title, :content,
                         :minimum => 8 

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end
    

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
        @categories = Category.all
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end





    def edit
        @post = Post.find(params[:id])
    end


    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end


    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    private  
    def post_params
        params.require(:post).permit(:title, :content, :category_id)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<% @title="Surfing// Redefined :Edit Post" %>
<h2 class="title text-info font-italic ">Edit Post</h2>

    <%= form_for @post, url: post_path, method: :patch do |f| %>
      <% if @post.errors.any? %>
       <% @post.errors.full_messages.each do |msg|%>
         <div class="alert alert-danger"><%= msg %></div>
          <% end %>
    <% end %>  
<br> 
      
      
      
      <%= f.label :Title %>:
        <%= f.text_field :title, {:class => "form-control"} %><br />
      
        <%= f.label :Content %>:
        <%= f.text_area :content, {:class => "form-control"} %><br />
      
        <%= f.submit({:class => "btn btn-primary"})%>
      <% end %>

app/views/posts/index.html.erb
<% @title="You're welcome to our surfing blog" %>

<h2 class="title text-info font-italic">Surfing Blog Posts</h2>
<br>


<div class="hero-unit">
<% @posts.each do |post| %>
  <h4 class = "text-dark"><%= post.title.titleize  %>
  <span class="badge badge-warning">New</span></h4>
  <p class= "text-secondary"><%= post.content.capitalize%></p>
  <p>
    <a class="btn btn-primary btn-large" href="<%= post_path(post) %>">
      Learn more
    </a>
  </p>
  <% end %>
</div>

app/views/posts/new.html.erb
<% @title="Surfing// Redefined: New Post" %>

<h2 class="title text-info font-italic ">Add Post</h2>

    <%= form_for @post, url: posts_path do |f| %>
      <% if @post.errors.any? %>
       <% @post.errors.full_messages.each do |msg|%>
         <div class="alert alert-danger"><%= msg %></div>
          <% end %>







    <% end %>  
<br> 
      
      
      
      <%= f.label :Title %>:
        <%= f.text_field :title, {:class => "form-control"} %><br />
      
        <%= f.label :Content %>:
        <%= f.text_area :content, {:class => "form-control"} %><br />

        <%= f.label :category_id %>:
        <%= f.collection_select :category_id, @categories, :id, :name %><br>
        
        <%= f.submit({:class => "btn btn-primary"})%>
      <% end %>

app/views/posts/show.html.erb
<% @title="Surfing// Redefined: Post" %>

<h2 class="title text-info font-italic"><%= @post.title %></h2>
<h5 class="text-secondary"><%= @post.content %></h5>
<h5><%= @post.category.name %></h5>  

<hr>




<div class="btn-group">
<%= link_to "Edit", edit_post_path(@post), :class => "btn btn-secondary"%>

<%= link_to "Delete", post_path(@post), 
 method: :delete,
 data: {confirm: "Are you sure you want to delete this post?"},
:class => "btn btn-info" %>
</div>


<%= render "comments/comments" %>
<%= render "comments/forms" %>