config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'posts#index', as: 'home'

   get 'about' => 'pages#about'

  resources :posts do
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= favicon_link_tag asset_path('favicon.png') %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <img src="https://images.vexels.com/media/users/3/142847/isolated/preview/a39a1b865f6f0a05b95fc3946f5df9b9-wave-surfing-beach-logo-by-vexels.png" width="55" alt="" class="d-inline-block  my-0 mr-md-auto">

  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="<%= home_path %>">Home</a>
    <a class="p-2 text-dark" href="<%= about_path %>">About</a>
    <a class="p-2 text-dark" href="<%= new_post_path %>">Create Post</a>

        <% if @current_user == nil %>
              <%= link_to "Sign Up", signup_path, class: "item" %>
              <%= link_to "Login", login_path, class: "item" %>
            <% else %>
              Welcome, <%= @current_user.username %>!
              <%= link_to "Logout", "/logout", method: :delete, class: "item" %>
            <% end %>
</div>

  </nav>






<div class="container">
<%= yield %>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>